// GSD DB Writer — Markdown generators + DB-first write helpers
//
// The missing DB→markdown direction. S03 established markdown→DB (md-importer.ts).
// This module generates DECISIONS.md and REQUIREMENTS.md from DB state,
// computes next decision IDs, and provides write helpers that upsert to DB
// then regenerate the corresponding markdown file.
//
// Critical invariant: generated markdown must round-trip through
// parseDecisionsTable() and parseRequirementsSections() with field fidelity.

import { dirname, isAbsolute, join, relative, resolve } from 'node:path';
import { readFileSync, existsSync } from 'node:fs';
import type { Decision, Requirement } from './types.js';
import { summarizeRequirementsCoverage } from './requirements-backlog.js';
import { gsdRoot, resolveGsdRootFile } from './paths.js';
import { writeProjectionFile } from './compat/compat-marker.js';
import { GSDError, GSD_STALE_STATE, GSD_IO_ERROR } from './errors.js';
import { logWarning, logError } from './workflow-logger.js';
import { invalidateStateCache } from './state.js';
import { renderStateProjection } from './workflow-projections.js';
import { clearPathCache } from './paths.js';
import { clearParseCache } from './files.js';
import type { MilestoneScope, GsdWorkspace } from './workspace.js';
import { createWorkspace, scopeMilestone } from './workspace.js';
import { createMemory } from './memory-store.js';
import { synthesizeDecisionMemoryContent } from './memory-backfill.js';
import { executeRecordDomainOperation } from './record-domain-operation.js';
import { internalPlanningInvocation, type PlanningInvocation } from './planning-invocation.js';
import { loadWriteGateSnapshot, shouldBlockRootArtifactSaveInSnapshot } from './bootstrap/write-gate.js';

// ─── Freeform Detection ───────────────────────────────────────────────────

/**
 * Detect whether a DECISIONS.md file is in canonical table format
 * (generated by generateDecisionsMd).
 *
 * Returns true only if the file starts with the canonical header
 * ("# Decisions Register") that generateDecisionsMd produces.
 * Files with freeform content — even if they contain an appended
 * decisions table section — return false so the freeform content
 * is preserved.
 */
export function isDecisionsTableFormat(content: string): boolean {
  // The canonical format always starts with "# Decisions Register"
  const firstLine = content.split('\n')[0]?.trim() ?? '';
  if (firstLine !== '# Decisions Register') return false;

  // Additionally verify the file has the canonical table header
  return content.includes('| # | When | Scope | Decision | Choice | Rationale | Revisable?');
}

/**
 * Generate a minimal decisions table section (header + rows) for appending
 * to a freeform DECISIONS.md file.
 */
function generateDecisionsAppendBlock(decisions: Decision[]): string {
  const lines: string[] = [];
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('## Decisions Table');
  lines.push('');
  lines.push('| # | When | Scope | Decision | Choice | Rationale | Revisable? | Made By |');
  lines.push('| --- | --- | --- | --- | --- | --- | --- | --- |');

  for (const d of decisions) {
    const cells = [
      d.id,
      d.when_context,
      d.scope,
      d.decision,
      d.choice,
      d.rationale,
      d.revisable,
      d.made_by ?? 'agent',
    ].map(cell => (cell ?? '')
      .replace(/\|/g, '\\|')
      .replace(/\r\n|\r|\n/g, '<br>'));
    lines.push(`| ${cells.join(' | ')} |`);
  }

  return lines.join('\n') + '\n';
}

// ─── Markdown Generators ──────────────────────────────────────────────────

/**
 * Generate full DECISIONS.md content from an array of Decision objects.
 * Produces the canonical format: H1 header, HTML comment block, table header,
 * separator, and one data row per decision.
 *
 * Column order: #, When, Scope, Decision, Choice, Rationale, Revisable?
 */
export function generateDecisionsMd(decisions: Decision[]): string {
  const lines: string[] = [];

  lines.push('# Decisions Register');
  lines.push('');
  lines.push('<!-- Append-only. Never edit or remove existing rows.');
  lines.push('     To reverse a decision, add a new row that supersedes it.');
  lines.push('     Read this file at the start of any planning or research phase. -->');
  lines.push('');
  lines.push('| # | When | Scope | Decision | Choice | Rationale | Revisable? | Made By |');
  lines.push('| --- | --- | --- | --- | --- | --- | --- | --- |');

  for (const d of decisions) {
    // Escape pipe characters within cell values to preserve table structure
    const cells = [
      d.id,
      d.when_context,
      d.scope,
      d.decision,
      d.choice,
      d.rationale,
      d.revisable,
      d.made_by ?? 'agent',
    ].map(cell => (cell ?? '')
      .replace(/\|/g, '\\|')
      .replace(/\r\n|\r|\n/g, '<br>'));

    lines.push(`| ${cells.join(' | ')} |`);
  }

  return lines.join('\n') + '\n';
}

// ─── Requirements Markdown Generator ──────────────────────────────────────

/** Status values that map to specific sections, in display order. */
const STATUS_SECTION_MAP: Array<{ status: string; heading: string }> = [
  { status: 'active', heading: 'Active' },
  { status: 'validated', heading: 'Validated' },
  { status: 'deferred', heading: 'Deferred' },
  { status: 'out-of-scope', heading: 'Out of Scope' },
];

/** Keep the later lines of a multi-line value inside its bullet. */
function indentLaterLines(value: string): string {
  return value.replace(/\n(?=[^\n])/g, '\n  ');
}

/**
 * Generate full REQUIREMENTS.md content from an array of Requirement objects.
 * Groups requirements by status into sections (## Active, ## Validated, etc.),
 * each containing ### RXXX — Description headings with bullet fields. Empty
 * status sections are emitted too because the deep-mode validator treats their
 * presence as part of the canonical contract.
 */
export function generateRequirementsMd(requirements: Requirement[]): string {
  const lines: string[] = [];

  lines.push('# Requirements');
  lines.push('');
  lines.push('This file is the explicit capability and coverage contract for the project.');
  lines.push('');

  // Group by status
  const byStatus = new Map<string, Requirement[]>();
  for (const r of requirements) {
    const status = (r.status || 'active').toLowerCase();
    if (!byStatus.has(status)) byStatus.set(status, []);
    byStatus.get(status)!.push(r);
  }

  // Emit sections in canonical order
  for (const { status, heading } of STATUS_SECTION_MAP) {
    const reqs = byStatus.get(status);
    lines.push(`## ${heading}`);
    lines.push('');

    for (const r of reqs ?? []) {
      lines.push(`### ${r.id} — ${r.description || 'Untitled'}`);

      // Emit bullet fields — only those with content
      if (r.class) lines.push(`- Class: ${r.class}`);
      if (r.status) lines.push(`- Status: ${r.status}`);
      if (r.description) lines.push(`- Description: ${indentLaterLines(r.description)}`);
      if (r.why) lines.push(`- Why it matters: ${indentLaterLines(r.why)}`);
      if (r.source) lines.push(`- Source: ${r.source}`);
      if (r.primary_owner) lines.push(`- Primary owning slice: ${r.primary_owner}`);
      if (r.supporting_slices) lines.push(`- Supporting slices: ${r.supporting_slices}`);
      if (r.validation) lines.push(`- Validation: ${indentLaterLines(r.validation)}`);
      if (r.notes) lines.push(`- Notes: ${indentLaterLines(r.notes)}`);
      lines.push('');
    }
  }

  // Traceability table
  lines.push('## Traceability');
  lines.push('');
  lines.push('| ID | Class | Status | Primary owner | Supporting | Proof |');
  lines.push('| --- | --- | --- | --- | --- | --- |');

  for (const r of requirements) {
    const proof = r.validation || 'unmapped';
    lines.push(
      `| ${r.id} | ${r.class || ''} | ${r.status || ''} | ${r.primary_owner || 'none'} | ${r.supporting_slices || 'none'} | ${proof} |`,
    );
  }

  lines.push('');

  // Coverage Summary
  const coverage = summarizeRequirementsCoverage(requirements);
  const validatedReqs = byStatus.get('validated') ?? [];
  const validatedIds = validatedReqs.map(r => r.id).join(', ');

  lines.push('## Coverage Summary');
  lines.push('');
  lines.push(`- Active requirements: ${coverage.active}`);
  lines.push(`- Mapped to slices: ${coverage.mappedToSlice}`);
  lines.push(`- Validated: ${validatedReqs.length}${validatedIds ? ` (${validatedIds})` : ''}`);
  lines.push(`- Unmapped active requirements: ${coverage.unmappedActive}`);

  return lines.join('\n') + '\n';
}

// ─── Next Decision ID ─────────────────────────────────────────────────────

/**
 * Compute the next decision ID from the current DB state.
 * Queries MAX(CAST(SUBSTR(id, 2) AS INTEGER)) from decisions table.
 * Returns D001 if no decisions exist. Zero-pads to 3 digits.
 */
export async function nextDecisionId(): Promise<string> {
  try {
    const db = await import('./gsd-db.js');
    const adapter = db._getAdapter();
    if (!adapter) return 'D001';

    const row = adapter
      .prepare('SELECT MAX(CAST(SUBSTR(id, 2) AS INTEGER)) as max_num FROM decisions')
      .get();

    const maxNum = row ? (row['max_num'] as number | null) : null;
    if (maxNum == null || isNaN(maxNum)) return 'D001';

    const next = maxNum + 1;
    return `D${String(next).padStart(3, '0')}`;
  } catch (err) {
    logError('manifest', 'nextDecisionId failed', { fn: 'nextDecisionId', error: String((err as Error).message) });
    return 'D001';
  }
}

/**
 * ADR-013 Stage 3: compute the next `D###` identifier across both the legacy
 * `decisions` table AND the `memories.structured_fields.sourceDecisionId`
 * surface. Returns the max numeric suffix from either side + 1, three-digit
 * padded.
 *
 * Used by `saveDecisionToDb` once writes to the `decisions` table stop —
 * new decisions live only in memories, but historical IDs sit in both
 * places during the cutover bake. The cross-surface max keeps IDs
 * monotonic and avoids collisions on the next save.
 */
function nextDecisionIdAcrossSurfaces(
  adapter: ReturnType<typeof import('./gsd-db.js')._getAdapter>,
): string {
  if (!adapter) return 'D001';

  let maxNum = 0;

  // Legacy table — best-effort.
  try {
    const row = adapter
      .prepare('SELECT MAX(CAST(SUBSTR(id, 2) AS INTEGER)) as max_num FROM decisions')
      .get();
    const candidate = row ? (row['max_num'] as number | null) : null;
    if (typeof candidate === 'number' && Number.isFinite(candidate)) {
      maxNum = Math.max(maxNum, candidate);
    }
  } catch {
    // fall through to memory-only
  }

  // Memory surface: scan structuredFields.sourceDecisionId for D### values.
  // SQLite LIKE on the JSON-stringified field is sufficient — rows tagged
  // with sourceDecisionId are bounded by the decisions count.
  try {
    const rows = adapter
      .prepare(
        "SELECT structured_fields FROM memories WHERE structured_fields LIKE '%\"sourceDecisionId\":\"D%'",
      )
      .all() as Array<{ structured_fields: string | null }>;
    for (const row of rows) {
      if (!row.structured_fields) continue;
      let sf: Record<string, unknown>;
      try {
        sf = JSON.parse(row.structured_fields) as Record<string, unknown>;
      } catch {
        continue;
      }
      const sourceId = sf['sourceDecisionId'];
      if (typeof sourceId !== 'string' || !sourceId.startsWith('D')) continue;
      const num = parseInt(sourceId.slice(1), 10);
      if (Number.isFinite(num) && num > maxNum) maxNum = num;
    }
  } catch {
    // best-effort
  }

  const next = maxNum + 1;
  return `D${String(next).padStart(3, '0')}`;
}

// ─── Next Requirement ID ─────────────────────────────────────────────────

/**
 * Compute the next requirement ID from the current DB state.
 * Queries MAX(CAST(SUBSTR(id, 2) AS INTEGER)) from requirements table.
 * Returns R001 if no requirements exist. Zero-pads to 3 digits.
 */
export async function nextRequirementId(): Promise<string> {
  try {
    const db = await import('./gsd-db.js');
    const adapter = db._getAdapter();
    if (!adapter) return 'R001';

    const row = adapter
      .prepare('SELECT MAX(CAST(SUBSTR(id, 2) AS INTEGER)) as max_num FROM requirements')
      .get();

    const maxNum = row ? (row['max_num'] as number | null) : null;
    if (maxNum == null || isNaN(maxNum)) return 'R001';

    const next = maxNum + 1;
    return `R${String(next).padStart(3, '0')}`;
  } catch (err) {
    logError('manifest', 'nextRequirementId failed', { fn: 'nextRequirementId', error: String((err as Error).message) });
    return 'R001';
  }
}

// ─── Save Requirement to DB + Regenerate Markdown ────────────────────────

export interface SaveRequirementFields {
  class: string;
  status?: string;
  description: string;
  why: string;
  source: string;
  primary_owner?: string;
  supporting_slices?: string;
  validation?: string;
  notes?: string;
}

/**
 * A requirement write changes REQUIREMENTS.md, so it waits for a pending
 * discussion gate. The check is here, in the writer both transports call, so
 * the native tool and the workflow MCP tool enforce the same rule.
 */
function assertRequirementsWriteAllowed(basePath: string): void {
  const guard = shouldBlockRootArtifactSaveInSnapshot(loadWriteGateSnapshot(basePath), 'REQUIREMENTS');
  if (guard.block) throw new RootArtifactWriteBlockedError(guard.reason ?? 'requirements write blocked');
}

/** The write gate refused a root artifact write. Tool handlers report `code` as the error. */
export class RootArtifactWriteBlockedError extends Error {
  readonly code = 'root_artifact_write_blocked';
}

/**
 * Save a new requirement through the requirement.save Domain Operation and
 * regenerate REQUIREMENTS.md. The ID is allocated inside the operation, so a
 * replay with the same idempotency key returns the original ID and writes
 * nothing.
 *
 * Returns the assigned ID.
 */
export async function saveRequirementToDb(
  fields: SaveRequirementFields,
  basePath: string,
  invocation: PlanningInvocation = internalPlanningInvocation(),
): Promise<{ id: string }> {
  assertRequirementsWriteAllowed(basePath);
  try {
    const db = await import('./gsd-db.js');

    // ID assignment and insert commit in one Domain Operation.
    const mutate = () => {
      const adapter = db._getAdapter();
      if (!adapter) throw new GSDError(GSD_STALE_STATE, "gsd-db: No database open");

      const existingRow = adapter
        .prepare(
          `SELECT * FROM requirements
           WHERE LOWER(TRIM(description)) = LOWER(TRIM(:description))
             AND LOWER(COALESCE(status, 'active')) = 'active'
             AND superseded_by IS NULL
           ORDER BY id
           LIMIT 1`,
        )
        .get({ ':description': fields.description });
      const row = adapter
        .prepare('SELECT MAX(CAST(SUBSTR(id, 2) AS INTEGER)) as max_num FROM requirements')
        .get();
      const maxNum = row ? (row['max_num'] as number | null) : null;
      const nextId = existingRow
        ? String(existingRow['id'])
        : (maxNum == null || isNaN(maxNum))
        ? 'R001'
        : `R${String(maxNum + 1).padStart(3, '0')}`;

      const requirement: Requirement = {
        id: nextId,
        class: fields.class || (existingRow?.['class'] as string | undefined) || '',
        status: fields.status ?? (existingRow?.['status'] as string | undefined) ?? 'active',
        description: fields.description,
        why: fields.why,
        source: fields.source,
        primary_owner: fields.primary_owner ?? (existingRow?.['primary_owner'] as string | undefined) ?? '',
        supporting_slices: fields.supporting_slices ?? (existingRow?.['supporting_slices'] as string | undefined) ?? '',
        validation: fields.validation ?? (existingRow?.['validation'] as string | undefined) ?? '',
        notes: fields.notes ?? (existingRow?.['notes'] as string | undefined) ?? '',
        full_content: (existingRow?.['full_content'] as string | undefined) ?? '',
        superseded_by: (existingRow?.['superseded_by'] as string | null | undefined) ?? null,
      };

      db.upsertRequirement(requirement);
      return { entityId: nextId, result: { id: nextId } };
    };
    const { id } = executeRecordDomainOperation({
      operationType: 'requirement.save',
      invocation,
      payload: fields,
      eventType: 'requirement.saved',
      entityType: 'requirement',
      projectionKeys: ['planning/requirements'],
      mutate,
    });

    try {
      await regenerateRequirementsMarkdown(basePath);
    } catch (diskErr) {
      logWarning('projection', 'REQUIREMENTS.md projection write failed; DB requirement remains committed', { fn: 'saveRequirementToDb', id, error: String((diskErr as Error).message) });
    }
    invalidateStateCache();
    clearPathCache();
    clearParseCache();
    await renderStateProjection(basePath);

    return { id };
  } catch (err) {
    logError('manifest', 'saveRequirementToDb failed', { fn: 'saveRequirementToDb', error: String((err as Error).message) });
    throw err;
  }
}

// ─── Async Mutex for Decision Saves ───────────────────────────────────────
//
// Serializes the entire saveDecisionToDb operation (ID generation + DB upsert
// + file read + markdown regeneration + file write) so that parallel callers
// cannot interleave and produce a last-writer-wins race on DECISIONS.md.
let _decisionSaveLock: Promise<unknown> = Promise.resolve();

/** Reset the mutex — only for tests. */
export function _resetDecisionSaveLock(): void {
  _decisionSaveLock = Promise.resolve();
}

export interface DecisionsProjectionIntent {
  path: string;
  content: string;
}

export async function readDecisionsProjectionIntent(
  basePath: string,
): Promise<DecisionsProjectionIntent | null> {
  const { getAllDecisionsFromMemories } = await import('./context-store.js');
  const allDecisions: Decision[] = getAllDecisionsFromMemories();
  const path = resolveGsdRootFile(basePath, 'DECISIONS');
  const existingContent = existsSync(path) ? readFileSync(path, 'utf-8') : null;
  if (allDecisions.length === 0 && existingContent === null) return null;

  if (existingContent && !isDecisionsTableFormat(existingContent)) {
    const marker = '---\n\n## Decisions Table';
    const markerIdx = existingContent.indexOf(marker);
    const freeformPart = markerIdx >= 0
      ? existingContent.substring(0, markerIdx).trimEnd()
      : existingContent.trimEnd();
    return {
      path,
      content: freeformPart + '\n' + generateDecisionsAppendBlock(allDecisions),
    };
  }

  return { path, content: generateDecisionsMd(allDecisions) };
}

/**
 * Re-project root DECISIONS.md from the authoritative decision records, with no
 * new decision being added. Mirrors the projection saveDecisionToDb performs
 * after a save, but over the full set — so a DB → markdown re-projection
 * (rebuild or reconcile) re-derives DECISIONS.md and never leaves it
 * showing a stale subset (e.g. after a worktree merge that accepted one
 * branch's DECISIONS.md while the DB holds the union of both branches'
 * decisions). DB stays the single source of truth; this only writes markdown.
 */
export async function regenerateDecisionsMarkdown(basePath: string): Promise<void> {
  const intent = await readDecisionsProjectionIntent(basePath);
  if (!intent) return;
  await writeProjectionFile(basePath, intent.path, intent.content, []);
}

/**
 * Re-project root REQUIREMENTS.md from the requirement rows, with no
 * requirement being added or changed. Writes nothing when there are no
 * requirement rows and no file, and returns false.
 */
export async function regenerateRequirementsMarkdown(basePath: string): Promise<boolean> {
  const db = await import('./gsd-db.js');
  const rows = db._getAdapter()?.prepare('SELECT * FROM requirements ORDER BY id').all() ?? [];
  const filePath = resolveGsdRootFile(basePath, 'REQUIREMENTS');
  if (rows.length === 0 && !existsSync(filePath)) return false;
  const requirements: Requirement[] = rows.map(row => ({
    id: row['id'] as string,
    class: row['class'] as string,
    status: row['status'] as string,
    description: row['description'] as string,
    why: row['why'] as string,
    source: row['source'] as string,
    primary_owner: row['primary_owner'] as string,
    supporting_slices: row['supporting_slices'] as string,
    validation: row['validation'] as string,
    notes: row['notes'] as string,
    full_content: row['full_content'] as string,
    superseded_by: (row['superseded_by'] as string) ?? null,
  }));
  await writeProjectionFile(
    basePath,
    filePath,
    generateRequirementsMd(requirements.filter(r => r.superseded_by == null)),
    [],
  );
  return true;
}

/**
 * Re-project the root narrative artifacts (PROJECT.md and the root drafts)
 * from their artifact rows. These types have no structured source: the row is
 * the content. REQUIREMENTS.md is not replayed from its row; it is rendered
 * from the requirement rows. Returns false when there is no such row.
 */
export async function regenerateRootArtifactsMarkdown(basePath: string): Promise<boolean> {
  const db = await import('./gsd-db.js');
  const rows = db._getAdapter()?.prepare(
    `SELECT artifact_type, full_content FROM artifacts
     WHERE milestone_id IS NULL
       AND artifact_type IN ('PROJECT', 'PROJECT-DRAFT', 'REQUIREMENTS-DRAFT')
       AND TRIM(full_content) != ''
     ORDER BY artifact_type`,
  ).all() ?? [];
  for (const row of rows) {
    await writeProjectionFile(
      basePath,
      join(gsdRoot(basePath), `${row['artifact_type'] as string}.md`),
      row['full_content'] as string,
      [],
    );
  }
  return rows.length > 0;
}

// ─── Save Decision to DB + Regenerate Markdown ────────────────────────────

export interface SaveDecisionFields {
  scope: string;
  decision: string;
  choice: string;
  rationale: string;
  revisable?: string;
  when_context?: string;
  made_by?: import('./types.js').DecisionMadeBy;
  /** ADR-011 Phase 2: origin of the decision — "discussion" (default), "planning", "escalation". */
  source?: string;
  /** ID of the active decision that this decision replaces (e.g. "D003"). */
  supersedes?: string;
}

/**
 * Mark the decision `oldId` as replaced by `newId`. Only an active decision
 * can be replaced, so every chain keeps exactly one active head.
 */
function supersedeActiveDecision(
  db: typeof import('./gsd-db.js'),
  oldId: string,
  newId: string,
): void {
  const row = db._getAdapter()?.prepare(
    `SELECT id, structured_fields FROM memories
     WHERE category = 'architecture'
       AND json_valid(structured_fields)
       AND json_extract(structured_fields, '$.sourceDecisionId') = :id
     ORDER BY seq DESC LIMIT 1`,
  ).get({ ':id': oldId });
  const fields = row ? JSON.parse(row['structured_fields'] as string) as Record<string, unknown> : null;
  if (!row || !fields || fields['deleted'] === true) {
    throw new Error(`Cannot supersede ${oldId}: no such decision.`);
  }
  if (fields['superseded_by']) {
    throw new Error(
      `Cannot supersede ${oldId}: it is already superseded by ${String(fields['superseded_by'])}. Supersede the active decision instead.`,
    );
  }
  db.updateMemoryStructuredFieldsRow(
    String(row['id']),
    { ...fields, superseded_by: newId },
    new Date().toISOString(),
  );
}

type NormalizedSaveDecisionFields = Omit<
  SaveDecisionFields,
  'when_context' | 'revisable' | 'made_by' | 'source'
> & {
  when_context: string;
  revisable: string;
  made_by: NonNullable<SaveDecisionFields['made_by']>;
  source: string;
};

/**
 * Save a new decision through the decision.save Domain Operation and
 * regenerate DECISIONS.md. The ID is allocated inside the operation, so a
 * replay with the same idempotency key returns the original ID and writes
 * nothing. A failed write throws and leaves DECISIONS.md untouched.
 *
 * Concurrency: uses an async mutex (promise chain) to serialize the
 * projection regen and file write so parallel callers in one process do not
 * overwrite each other's output (last-writer-wins race condition).
 */
export async function saveDecisionToDb(
  fields: SaveDecisionFields,
  basePath: string,
  invocation: PlanningInvocation = internalPlanningInvocation(),
): Promise<{ id: string }> {
  // Serialize via async mutex: each call waits for the previous one to
  // complete before starting, preventing interleaved DB + file writes.
  let release: () => void;
  const prev = _decisionSaveLock;
  _decisionSaveLock = new Promise<void>(r => { release = r; });

  try {
    await prev;
  } catch {
    // Previous call failed — proceed regardless; the lock chain must continue.
  }

  try {
    const db = await import('./gsd-db.js');
    const adapter = db._getAdapter();
    const normalized: NormalizedSaveDecisionFields = {
      ...fields,
      when_context: fields.when_context ?? '',
      revisable: fields.revisable ?? 'Yes',
      made_by: fields.made_by ?? 'agent',
      source: fields.source ?? 'discussion',
    };

    // ADR-013 Stage 3 (destructive): writes to the `decisions` table stop
    // here. New decisions live only in the `memories` table; the projection
    // regen below sources from memories (Stage 2a). The decisions table
    // remains for backwards-compat reads (queryDecisions, md-importer,
    // commands-inspect, workflow-manifest) until #5756 drops it.
    //
    // Reversal: a code revert of this change restores the upsertDecision
    // call. Memory rows written between merge and revert stay durable; the
    // legacy table simply doesn't grow during the cutover window.
    //
    // The ID and the memory row commit in one Domain Operation. A failed
    // memory write aborts the operation.
    // Decision text never changes lifecycle status: a slice is cancelled
    // only through its own Domain Operation (gsd_skip_slice).
    const { decisionId: id } = executeRecordDomainOperation({
      operationType: 'decision.save',
      invocation,
      payload: normalized,
      eventType: 'decision.saved',
      entityType: 'decision',
      projectionKeys: ['decisions'],
      mutate: () => {
        const decisionId = nextDecisionIdAcrossSurfaces(adapter);
        if (normalized.supersedes) {
          supersedeActiveDecision(db, normalized.supersedes, decisionId);
        }
        if (!persistDecisionToMemory(decisionId, normalized)) {
          throw new Error(`Unable to persist decision ${decisionId}`);
        }
        return { entityId: decisionId, result: { decisionId } };
      },
    });

    // Fetch all decisions (including superseded for the full register).
    // ADR-013 Stage 2a: source from the `memories` table; the backfill
    // (memory-backfill.ts) absorbs the historical chain and drift-heals
    // superseded_by on every session start.
    const { getAllDecisionsFromMemories } = await import('./context-store.js');
    const allDecisions: Decision[] = getAllDecisionsFromMemories();

    const filePath = resolveGsdRootFile(basePath, 'DECISIONS');

    // Check if existing DECISIONS.md has freeform (non-table) content.
    // If so, preserve that content and append/update the decisions table
    // at the end instead of overwriting the entire file.
    let existingContent: string | null = null;
    if (existsSync(filePath)) {
      existingContent = readFileSync(filePath, 'utf-8');
    }

    let md: string;
    if (existingContent && !isDecisionsTableFormat(existingContent)) {
      // Freeform content detected — preserve it and append decisions table.
      // Strip any previously appended decisions table section to avoid duplication.
      const marker = '---\n\n## Decisions Table';
      const markerIdx = existingContent.indexOf(marker);
      const freeformPart = markerIdx >= 0
        ? existingContent.substring(0, markerIdx).trimEnd()
        : existingContent.trimEnd();
      md = freeformPart + '\n' + generateDecisionsAppendBlock(allDecisions);
    } else {
      // Table format or no existing file — full regeneration (original behavior)
      md = generateDecisionsMd(allDecisions);
    }

    try {
      await writeProjectionFile(basePath, filePath, md, []);
    } catch (diskErr) {
      logWarning('projection', 'DECISIONS.md projection write failed; DB decision remains committed', { fn: 'saveDecisionToDb', id, error: String((diskErr as Error).message) });
    }
    // Invalidate file-read caches so deriveState() sees the updated markdown.
    // Do NOT clear the artifacts table — we just wrote to it intentionally.
    invalidateStateCache();
    clearPathCache();
    clearParseCache();
    await renderStateProjection(basePath);

    return { id };
  } catch (err) {
    logError('manifest', 'saveDecisionToDb failed', { fn: 'saveDecisionToDb', error: String((err as Error).message) });
    throw err;
  } finally {
    release!();
  }
}

function persistDecisionToMemory(
  id: string,
  normalizedFields: NormalizedSaveDecisionFields,
): boolean {
  const content = synthesizeDecisionMemoryContent(normalizedFields);
  if (!content) return false;

  return createMemory({
    category: 'architecture',
    content,
    scope: normalizedFields.scope || 'project',
    confidence: 0.85,
    structuredFields: {
      sourceDecisionId: id,
      when_context: normalizedFields.when_context,
      scope: normalizedFields.scope,
      decision: normalizedFields.decision,
      choice: normalizedFields.choice,
      rationale: normalizedFields.rationale,
      made_by: normalizedFields.made_by,
      revisable: normalizedFields.revisable,
      superseded_by: null,
    },
  }) !== null;
}

// ─── Update Requirement in DB + Regenerate Markdown ───────────────────────

/**
 * Update a requirement through the requirement.update Domain Operation and
 * regenerate REQUIREMENTS.md. The operation fetches the existing requirement,
 * merges the updates and upserts. A replay writes nothing.
 */
export async function updateRequirementInDb(
  id: string,
  updates: Partial<Requirement>,
  basePath: string,
  invocation: PlanningInvocation = internalPlanningInvocation(),
): Promise<void> {
  assertRequirementsWriteAllowed(basePath);
  try {
    const db = await import('./gsd-db.js');

    executeRecordDomainOperation({
      operationType: 'requirement.update',
      invocation,
      payload: { id, updates },
      eventType: 'requirement.updated',
      entityType: 'requirement',
      projectionKeys: ['planning/requirements'],
      mutate: () => {
        const existing = db.getRequirementById(id);

        const base: Requirement = existing ?? {
          id,
          class: '',
          status: 'active',
          description: '',
          why: '',
          source: '',
          primary_owner: '',
          supporting_slices: '',
          validation: '',
          notes: '',
          full_content: '',
          superseded_by: null,
        };

        // Merge updates into existing (or skeleton)
        const merged: Requirement = {
          ...base,
          ...updates,
          id: base.id, // ID cannot be changed
        };

        db.upsertRequirement(merged);
        return { entityId: id, result: { id } };
      },
    });

    try {
      await regenerateRequirementsMarkdown(basePath);
    } catch (diskErr) {
      logWarning('projection', 'REQUIREMENTS.md projection write failed; DB requirement update remains committed', { fn: 'updateRequirementInDb', id, error: String((diskErr as Error).message) });
    }
    // Invalidate file-read caches so deriveState() sees the updated markdown.
    // Do NOT clear the artifacts table — we just wrote to it intentionally.
    invalidateStateCache();
    clearPathCache();
    clearParseCache();
    await renderStateProjection(basePath);
  } catch (err) {
    logError('manifest', 'updateRequirementInDb failed', { fn: 'updateRequirementInDb', error: String((err as Error).message) });
    throw err;
  }
}

// ─── Save Artifact to DB + Disk ───────────────────────────────────────────

export interface SaveArtifactOpts {
  path: string;
  artifact_type: string;
  content: string;
  milestone_id?: string;
  slice_id?: string;
  task_id?: string;
}

/**
 * Commits the artifacts row of a save. A tool call passes a function that runs
 * `insertRow` inside its Domain Operation, with the content when the operation
 * decides it. The default writes the row alone.
 */
export type ArtifactRowStore = (insertRow: (content?: string) => void) => void;

const storeArtifactRowAlone: ArtifactRowStore = (insertRow) => insertRow();

/**
 * Save a root-level artifact (no milestone) to DB and write to disk,
 * routing path construction through workspace.contract.projectGsd directly.
 * Use this instead of saveArtifactToDbByScope when milestone_id is absent.
 */
export async function saveArtifactToDbForWorkspace(
  workspace: GsdWorkspace,
  opts: SaveArtifactOpts,
  storeRow: ArtifactRowStore = storeArtifactRowAlone,
): Promise<void> {
  try {
    const db = await import('./gsd-db.js');

    const gsdDir = workspace.contract.projectGsd;
    const fullPath = resolve(gsdDir, opts.path);

    const rel0 = relative(gsdDir, fullPath);
    if (rel0.startsWith('..') || isAbsolute(rel0)) {
      throw new GSDError(GSD_IO_ERROR, `saveArtifactToDbForWorkspace: path escapes .gsd/ directory: ${opts.path}`);
    }

    let contentToPersist = opts.content;
    if (opts.artifact_type === 'REQUIREMENTS' && opts.path === 'REQUIREMENTS.md') {
      const activeRequirements = db.getActiveRequirements();
      if (activeRequirements.length === 0) {
        throw new GSDError(GSD_STALE_STATE, 'saveArtifactToDbForWorkspace: REQUIREMENTS final save requires active DB-backed requirements');
      }
      contentToPersist = generateRequirementsMd(activeRequirements);
    }

    storeRow((content = contentToPersist) => db.insertArtifact({
      path: opts.path,
      artifact_type: opts.artifact_type,
      milestone_id: null,
      slice_id: null,
      task_id: null,
      full_content: content,
    }));

    try {
      const basePath = dirname(gsdDir);
      // A replayed call writes no row: the file follows the row that is stored.
      await writeProjectionFile(basePath, fullPath, db.getArtifact(opts.path)?.full_content ?? contentToPersist, []);
    } catch (diskErr) {
      logWarning('projection', 'artifact projection write failed; DB artifact remains committed', { fn: 'saveArtifactToDbForWorkspace', path: opts.path, error: String((diskErr as Error).message) });
    }
    invalidateStateCache();
    clearPathCache();
    clearParseCache();
  } catch (err) {
    logError('manifest', 'saveArtifactToDbForWorkspace failed', { fn: 'saveArtifactToDbForWorkspace', error: String((err as Error).message) });
    throw err;
  }
}

/**
 * Save an artifact to DB and write the corresponding markdown file to disk,
 * routing all path construction through the workspace contract.
 *
 * The path is relative to .gsd/ (e.g. "milestones/M001/slices/S06/tasks/T01-SUMMARY.md").
 * The full file path is computed as scope.workspace.contract.projectGsd + '/' + path.
 */
export async function saveArtifactToDbByScope(
  scope: MilestoneScope,
  opts: SaveArtifactOpts,
  storeRow: ArtifactRowStore = storeArtifactRowAlone,
): Promise<void> {
  // Guard: an empty milestoneId produces malformed paths (milestoneDir = join(gsd, "milestones", "")).
  // Callers that have no milestone should use saveArtifactToDbForWorkspace instead.
  if (!scope.milestoneId) {
    throw new GSDError(GSD_IO_ERROR, `saveArtifactToDbByScope: milestoneId is empty — use saveArtifactToDbForWorkspace for root artifacts`);
  }

  try {
    const db = await import('./gsd-db.js');

    // Use contract.projectGsd as the canonical .gsd directory — never a hand-rolled basePath join.
    const gsdDir = scope.workspace.contract.projectGsd;
    const fullPath = resolve(gsdDir, opts.path);

    // Guard against path traversal before any reads/writes
    const rel1 = relative(gsdDir, fullPath);
    if (rel1.startsWith('..') || isAbsolute(rel1)) {
      throw new GSDError(GSD_IO_ERROR, `saveArtifactToDbByScope: path escapes .gsd/ directory: ${opts.path}`);
    }

    let contentToPersist = opts.content;
    if (opts.artifact_type === 'REQUIREMENTS' && opts.path === 'REQUIREMENTS.md') {
      const activeRequirements = db.getActiveRequirements();
      if (activeRequirements.length === 0) {
        throw new GSDError(GSD_STALE_STATE, 'saveArtifactToDbByScope: REQUIREMENTS final save requires active DB-backed requirements');
      }
      contentToPersist = generateRequirementsMd(activeRequirements);
    }

    storeRow((content = contentToPersist) => db.insertArtifact({
      path: opts.path,
      artifact_type: opts.artifact_type,
      milestone_id: opts.milestone_id ?? null,
      slice_id: opts.slice_id ?? null,
      task_id: opts.task_id ?? null,
      full_content: content,
    }));

    // The DB row is the authority, so the file always follows it (a replayed
    // call writes no row). A file that changed outside GSD is kept by the
    // projection mutation guard, not here.
    try {
      const basePath = dirname(gsdDir);
      await writeProjectionFile(
        basePath,
        fullPath,
        db.getArtifact(opts.path)?.full_content ?? contentToPersist,
        [
          opts.milestone_id,
          opts.slice_id && `${opts.milestone_id}/${opts.slice_id}`,
          opts.task_id && `${opts.milestone_id}/${opts.slice_id}/${opts.task_id}`,
        ].filter((entity): entity is string => Boolean(entity)),
      );
    } catch (diskErr) {
      logWarning('projection', 'artifact projection write failed; DB artifact remains committed', { fn: 'saveArtifactToDbByScope', path: opts.path, error: String((diskErr as Error).message) });
    }
    // Invalidate file-read caches so deriveState() sees the updated markdown.
    // Do NOT clear the artifacts table — we just wrote to it intentionally.
    invalidateStateCache();
    clearPathCache();
    clearParseCache();
  } catch (err) {
    logError('manifest', 'saveArtifactToDbByScope failed', { fn: 'saveArtifactToDbByScope', error: String((err as Error).message) });
    throw err;
  }
}

/**
 * Save an artifact to DB and write the corresponding markdown file to disk.
 * The path is relative to .gsd/ (e.g. "milestones/M001/slices/S06/tasks/T01-SUMMARY.md").
 * The full file path is computed as basePath + '.gsd/' + path.
 *
 * @deprecated Use saveArtifactToDbByScope instead, which routes through the
 * workspace contract for canonical path resolution.
 * TODO(C-future): remove this legacy wrapper once all callers are migrated.
 */
export async function saveArtifactToDb(
  opts: SaveArtifactOpts,
  basePath: string,
  storeRow?: ArtifactRowStore,
): Promise<void> {
  const workspace = createWorkspace(basePath);
  const milestoneId = opts.milestone_id;
  if (milestoneId) {
    return saveArtifactToDbByScope(scopeMilestone(workspace, milestoneId), opts, storeRow);
  }
  return saveArtifactToDbForWorkspace(workspace, opts, storeRow);
}
