// Project/App: gsd-pi
// File Purpose: Publication module — push and draft-PR creation for a merged milestone (ADR-034).
//
// Publication is distinct from the merge verb: merging a milestone branch is a
// Worktree Lifecycle concern (worktree, branch, lease, stash discipline);
// publication needs only the resulting commit, a remote, and preferences.
// Extracted from the tail of `mergeMilestoneToMain` (auto-worktree.ts) so it is
// testable without a merge fixture and reachable from any closeout path.
//
// Publication failure is non-fatal to a completed local merge: every failure is
// logged and reported in the result, never thrown.

import { execFileSync } from "node:child_process";
import { randomUUID } from "node:crypto";

import {
  buildPullRequestEvidence,
  createDraftPullRequestFromEvidence,
} from "./pull-request-process.js";
import { emitJournalEvent } from "./journal.js";
import { hasPendingIntegrationPush, settleIntegrationPush } from "./milestone-closeout-effects.js";
import { logWarning } from "./workflow-logger.js";

export interface PublicationPrefs {
  autoPush: boolean;
  autoPr: boolean;
  remote?: string;
  prTargetBranch?: string;
}

export interface PublicationRequest {
  basePath: string;
  milestoneId: string;
  milestoneTitle: string;
  /** The branch the milestone was merged to (push target for auto-push). */
  integrationBranch: string;
  /** The milestone branch (push + PR head for auto-PR). */
  milestoneBranch: string;
  /** Pre-rendered per-slice summary blocks for the PR body. */
  sliceSummaries: readonly string[];
  /** True when the merge found nothing to commit — publication is skipped. */
  nothingToCommit: boolean;
  prefs: PublicationPrefs;
}

export interface PublicationResult {
  pushed: boolean;
  /** Set when a push was attempted and failed. Absent when no push ran. */
  pushError?: string;
  prCreated: boolean;
  prUrl?: string;
}

export function gitRemoteExists(basePath: string, remote: string): boolean {
  try {
    execFileSync("git", ["remote", "get-url", remote], {
      cwd: basePath,
      stdio: ["ignore", "pipe", "pipe"],
      encoding: "utf-8",
    });
    return true;
  } catch {
    return false;
  }
}

/**
 * Publish a merged milestone per preferences: push the integration branch
 * (auto-push, suppressed when auto-PR owns the remote interaction) and/or
 * push the milestone branch and open a draft PR (auto-PR).
 */
export function publishMilestone(request: PublicationRequest): PublicationResult {
  const result: PublicationResult = { pushed: false, prCreated: false };
  // A push that failed at an earlier closeout is retried even when this
  // merge committed nothing.
  if (request.nothingToCommit && !hasPendingIntegrationPush(request.integrationBranch)) return result;

  const { basePath, prefs } = request;
  const remote = prefs.remote ?? "origin";

  if (prefs.autoPush && !prefs.autoPr && gitRemoteExists(basePath, remote)) {
    Object.assign(result, pushIntegrationBranch(basePath, remote, request.integrationBranch, request.milestoneId));
  }
  if (request.nothingToCommit) return result;

  // #2302: PR creation is not gated on pushed/auto-push.
  if (prefs.autoPr && gitRemoteExists(basePath, remote)) {
    try {
      // Push the milestone branch to remote first
      execFileSync("git", ["push", remote, request.milestoneBranch], {
        cwd: basePath,
        stdio: ["ignore", "pipe", "pipe"],
        encoding: "utf-8",
      });
      const prEvidence = buildPullRequestEvidence({
        milestoneId: request.milestoneId,
        milestoneTitle: request.milestoneTitle,
        changeType: "feat",
        summaries: [...request.sliceSummaries],
        testsRun: ["Auto-created after milestone merge. Run `npm run verify:merge` before marking this draft ready."],
        rollbackNotes: ["Close the draft PR or revert the merge commit if review finds a behavior regression."],
        how: "Generated by git.auto_pr after the milestone branch was pushed and merged locally.",
      });
      const prUrl = createDraftPullRequestFromEvidence(basePath, request.milestoneId, prEvidence, {
        head: request.milestoneBranch,
        base: prefs.prTargetBranch ?? request.integrationBranch,
      });
      if (!prUrl) {
        throw new Error("gh pr create returned no URL");
      }
      result.prCreated = true;
      result.prUrl = prUrl;
    } catch (err) {
      // PR creation failure is non-fatal — gh may not be installed or authenticated
      logWarning("worktree", `PR creation failed: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  return result;
}

export interface PushIfAheadRequest {
  basePath: string;
  /** The integration branch to push (e.g. main). Empty disables the push. */
  branch: string;
  /** Optional milestone id for the journal event payload. */
  milestoneId?: string;
  prefs: PublicationPrefs;
}

export interface PushIfAheadResult {
  pushed: boolean;
  /** Set when a push was attempted and failed. Absent when no push ran. */
  pushError?: string;
}

/**
 * True when HEAD has commits not on its upstream. A branch with no upstream
 * was never pushed, so it counts as ahead; other rev-list failures
 * conservatively report not-ahead so closeout never wedges on inspection
 * errors (#2153).
 */
function isAheadOfUpstream(basePath: string): boolean {
  try {
    return execFileSync("git", ["rev-list", "--count", "@{upstream}..HEAD"], {
      cwd: basePath,
      stdio: ["ignore", "pipe", "pipe"],
      encoding: "utf-8",
    }).trim() !== "0";
  } catch (err) {
    const errWithStderr = err as { stderr?: string | Buffer };
    const stderr = errWithStderr.stderr?.toString() ?? "";
    const message = err instanceof Error ? err.message : String(err);
    return /no upstream configured/i.test(`${stderr}\n${message}`);
  }
}

/**
 * Auto-push tail-step for closeout paths that never reach `publishMilestone`
 * (the isolation=none merge skip and the already-merged fast path — #2153).
 * Mirrors publishMilestone's autoPush branch: `git push <remote> <branch>`
 * with the same remote resolution (prefs.remote ?? "origin") and the same
 * non-fatal failure contract. No-ops when auto-push is off (suppressed by
 * auto-PR, as in publishMilestone), the branch is empty, the remote is
 * missing, or the branch is not ahead of its upstream.
 */
export function pushIntegrationBranchIfAhead(
  request: PushIfAheadRequest,
): PushIfAheadResult {
  const result: PushIfAheadResult = { pushed: false };
  const { basePath, branch, prefs } = request;
  if (!branch || !prefs.autoPush || prefs.autoPr) return result;
  const remote = prefs.remote ?? "origin";
  if (!gitRemoteExists(basePath, remote)) return result;
  if (!isAheadOfUpstream(basePath)) return result;

  return pushIntegrationBranch(basePath, remote, branch, request.milestoneId);
}

/**
 * Push the integration branch and record the outcome: a `milestone-pushed`
 * journal event, and on success the Settlement Receipt of every merged
 * Milestone still waiting for this push. A failed push leaves those effects
 * without a receipt, so the next closeout pushes again.
 */
function pushIntegrationBranch(
  basePath: string,
  remote: string,
  branch: string,
  milestoneId: string | undefined,
): PushIfAheadResult {
  const result: PushIfAheadResult = { pushed: false };
  try {
    execFileSync("git", ["push", remote, branch], {
      cwd: basePath,
      stdio: ["ignore", "pipe", "pipe"],
      encoding: "utf-8",
    });
    result.pushed = true;
  } catch (err) {
    // Push failure is non-fatal — closeout must not wedge on it (#2153)
    result.pushError = err instanceof Error ? err.message : String(err);
    logWarning("worktree", `git push failed: ${result.pushError}`);
  }
  emitJournalEvent(basePath, {
    ts: new Date().toISOString(),
    flowId: randomUUID(),
    seq: 0,
    eventType: "milestone-pushed",
    data: {
      milestoneId,
      branch,
      remote,
      pushed: result.pushed,
      error: result.pushError,
    },
  });
  if (result.pushed) {
    try {
      settleIntegrationPush({ projectRoot: basePath, remote, integrationBranch: branch });
    } catch (err) {
      // The push effect keeps no receipt, so the next closeout pushes again.
      logWarning("worktree", `push receipt was not recorded: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
  return result;
}
